// Code generated by MockGen. DO NOT EDIT.
// Source: internal/openai/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/openai/client.go -destination internal/mocks/client_mock.go
//

// Package mock_openai is a generated GoMock package.
package mock_openai

import (
	config "cli_agent/internal/config"
	logger "cli_agent/internal/logger"
	context "context"
	reflect "reflect"

	openai "github.com/openai/openai-go/v3"
	option "github.com/openai/openai-go/v3/option"
	gomock "go.uber.org/mock/gomock"
)

// MockCLIClient is a mock of CLIClient interface.
type MockCLIClient struct {
	ctrl     *gomock.Controller
	recorder *MockCLIClientMockRecorder
	isgomock struct{}
}

// MockCLIClientMockRecorder is the mock recorder for MockCLIClient.
type MockCLIClientMockRecorder struct {
	mock *MockCLIClient
}

// NewMockCLIClient creates a new mock instance.
func NewMockCLIClient(ctrl *gomock.Controller) *MockCLIClient {
	mock := &MockCLIClient{ctrl: ctrl}
	mock.recorder = &MockCLIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCLIClient) EXPECT() *MockCLIClientMockRecorder {
	return m.recorder
}

// GetCLIConfig mocks base method.
func (m *MockCLIClient) GetCLIConfig() config.CLIConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCLIConfig")
	ret0, _ := ret[0].(config.CLIConfig)
	return ret0
}

// GetCLIConfig indicates an expected call of GetCLIConfig.
func (mr *MockCLIClientMockRecorder) GetCLIConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCLIConfig", reflect.TypeOf((*MockCLIClient)(nil).GetCLIConfig))
}

// GetLogger mocks base method.
func (m *MockCLIClient) GetLogger() logger.CLILogger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogger")
	ret0, _ := ret[0].(logger.CLILogger)
	return ret0
}

// GetLogger indicates an expected call of GetLogger.
func (mr *MockCLIClientMockRecorder) GetLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogger", reflect.TypeOf((*MockCLIClient)(nil).GetLogger))
}

// GetModel mocks base method.
func (m *MockCLIClient) GetModel(ctx context.Context, modelID string) (*openai.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModel", ctx, modelID)
	ret0, _ := ret[0].(*openai.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModel indicates an expected call of GetModel.
func (mr *MockCLIClientMockRecorder) GetModel(ctx, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModel", reflect.TypeOf((*MockCLIClient)(nil).GetModel), ctx, modelID)
}

// ListModels mocks base method.
func (m *MockCLIClient) ListModels(ctx context.Context) ([]openai.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModels", ctx)
	ret0, _ := ret[0].([]openai.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModels indicates an expected call of ListModels.
func (mr *MockCLIClientMockRecorder) ListModels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModels", reflect.TypeOf((*MockCLIClient)(nil).ListModels), ctx)
}

// NewCompletion mocks base method.
func (m *MockCLIClient) NewCompletion(ctx context.Context, body openai.ChatCompletionNewParams, opts ...option.RequestOption) (*openai.ChatCompletion, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewCompletion", varargs...)
	ret0, _ := ret[0].(*openai.ChatCompletion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewCompletion indicates an expected call of NewCompletion.
func (mr *MockCLIClientMockRecorder) NewCompletion(ctx, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCompletion", reflect.TypeOf((*MockCLIClient)(nil).NewCompletion), varargs...)
}
