package parser

import (
	"testing"
)

func TestExtractBashCommand(t *testing.T) {
	tests := []struct {
		name        string
		input       string
		expected    string
		expectError error
	}{
		{
			name:        "valid bash code block with simple command",
			input:       "Here's a command to run:\n```bash\nls -la\n```",
			expected:    "ls -la",
			expectError: nil,
		},
		{
			name:        "valid bash code block with extra whitespace",
			input:       "```bash\n  ls -la  \n```",
			expected:    "ls -la",
			expectError: ErrTrimmableWhitespaces,
		},
		{
			name:        "non strict bash code block with multi-line command",
			input:       "```bash\ncd /tmp\nls -la\n```",
			expected:    "cd /tmp\nls -la",
			expectError: nil,
		},
		{
			name:        "valid bash code block with complex command",
			input:       "```bash\ngrep -r \"pattern\" /path/to/dir --include=\"*.go\"\n```",
			expected:    `grep -r "pattern" /path/to/dir --include="*.go"`,
			expectError: nil,
		},
		{
			name:        "no code blocks",
			input:       "This is just plain text without any code blocks",
			expected:    "",
			expectError: ErrNoStrictBashBlock,
		},
		{
			name:        "code block with different language",
			input:       "```go\nfunc main() {\n\tfmt.Println(\"Hello\")\n}\n```",
			expected:    "",
			expectError: ErrNoStrictBashBlock,
		},
		{
			name:        "empty bash code block",
			input:       "```bash\n\n```",
			expected:    "",
			expectError: ErrEmptyBashBlock,
		},
		{
			name:        "bash code block with only whitespace",
			input:       "```bash\n   \n   \n```",
			expected:    "",
			expectError: ErrTrimmableWhitespaces,
		},
		{
			name:        "multiple bash code blocks",
			input:       "```bash\nls -la\n```\n\n```bash\ncd /tmp\n```",
			expected:    "",
			expectError: ErrMultipleBashCommands,
		},
		{
			name:        "bash code block with text before and after",
			input:       "Some text before\n```bash\necho hello\n```\nSome text after",
			expected:    "echo hello",
			expectError: nil,
		},
		{
			name:        "bash code block with pipe command",
			input:       "```bash\ncat file.txt | grep pattern\n```",
			expected:    "cat file.txt | grep pattern",
			expectError: nil,
		},
		{
			name:        "bash code block with command substitution",
			input:       "```bash\necho $(date)\n```",
			expected:    "echo $(date)",
			expectError: nil,
		},
		{
			name:        "bash code block with heredoc",
			input:       "```bash\ncat <<EOF\nHello World\nEOF\n```",
			expected:    "cat <<EOF\nHello World\nEOF",
			expectError: nil,
		},
		{
			name:        "bash code block with environment variable",
			input:       "```bash\nexport PATH=/usr/local/bin:$PATH\n```",
			expected:    "export PATH=/usr/local/bin:$PATH",
			expectError: nil,
		},
		{
			name:        "bash code block with background job",
			input:       "```bash\nnohup ./script.sh &\n```",
			expected:    "nohup ./script.sh &",
			expectError: nil,
		},
		{
			name:        "bash code block with conditional",
			input:       "```bash\nif [ -f file.txt ]; then\n  cat file.txt\nfi\n```",
			expected:    "if [ -f file.txt ]; then\n  cat file.txt\nfi",
			expectError: nil,
		},
		{
			name:        "bash code block with loop",
			input:       "```bash\nfor i in {1..5}; do\n  echo $i\ndone\n```",
			expected:    "for i in {1..5}; do\n  echo $i\ndone",
			expectError: nil,
		},
		{
			name:        "bash code block with function definition",
			input:       "```bash\nfunction greet() {\n  echo \"Hello, $1!\"\n}\ngreet World\n```",
			expected:    "function greet() {\n  echo \"Hello, $1!\"\n}\ngreet World",
			expectError: nil,
		},
		{
			name:        "bash code block with array",
			input:       "```bash\narr=(one two three)\necho ${arr[0]}\n```",
			expected:    "arr=(one two three)\necho ${arr[0]}",
			expectError: nil,
		},
		{
			name:        "bash code block with case statement",
			input:       "```bash\ncase $1 in\n  start) echo Starting;;\n  stop) echo Stopping;;\n  *) echo Usage;;\nesac\n```",
			expected:    "case $1 in\n  start) echo Starting;;\n  stop) echo Stopping;;\n  *) echo Usage;;\nesac",
			expectError: nil,
		},
		{
			name:        "bash code block with sudo command",
			input:       "```bash\nsudo apt-get update\n```",
			expected:    "sudo apt-get update",
			expectError: nil,
		},
		{
			name:        "bash code block with redirection",
			input:       "```bash\necho output > file.txt\n```",
			expected:    "echo output > file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with append redirection",
			input:       "```bash\necho more output >> file.txt\n```",
			expected:    "echo more output >> file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with error redirection",
			input:       "```bash\ncmd 2> error.log\n```",
			expected:    "cmd 2> error.log",
			expectError: nil,
		},
		{
			name:        "bash code block with combined redirection",
			input:       "```bash\ncmd > output.log 2>&1\n```",
			expected:    "cmd > output.log 2>&1",
			expectError: nil,
		},
		{
			name:        "bash code block with logical AND",
			input:       "```bash\ncmd1 && cmd2\n```",
			expected:    "cmd1 && cmd2",
			expectError: nil,
		},
		{
			name:        "bash code block with logical OR",
			input:       "```bash\ncmd1 || cmd2\n```",
			expected:    "cmd1 || cmd2",
			expectError: nil,
		},
		{
			name:        "bash code block with semicolon separator",
			input:       "```bash\ncmd1; cmd2; cmd3\n```",
			expected:    "cmd1; cmd2; cmd3",
			expectError: nil,
		},
		{
			name:        "bash code block with command grouping",
			input:       "```bash\n{ cmd1; cmd2; }\n```",
			expected:    "{ cmd1; cmd2; }",
			expectError: nil,
		},
		{
			name:        "bash code block with subshell",
			input:       "```bash\n(cmd1; cmd2)\n```",
			expected:    "(cmd1; cmd2)",
			expectError: nil,
		},
		{
			name:        "bash code block with variable assignment",
			input:       "```bash\nMY_VAR=\"some value\"\necho $MY_VAR\n```",
			expected:    "MY_VAR=\"some value\"\necho $MY_VAR",
			expectError: nil,
		},
		{
			name:        "bash code block with arithmetic",
			input:       "```bash\necho $((1 + 2))\n```",
			expected:    "echo $((1 + 2))",
			expectError: nil,
		},
		{
			name:        "bash code block with test command",
			input:       "```bash\n[ -f file.txt ] && echo exists\n```",
			expected:    "[ -f file.txt ] && echo exists",
			expectError: nil,
		},
		{
			name:        "bash code block with double bracket test",
			input:       "```bash\n[[ -f file.txt ]] && echo exists\n```",
			expected:    "[[ -f file.txt ]] && echo exists",
			expectError: nil,
		},
		{
			name:        "bash code block with find command",
			input:       "```bash\nfind /path -name \"*.go\" -type f\n```",
			expected:    "find /path -name \"*.go\" -type f",
			expectError: nil,
		},
		{
			name:        "bash code block with xargs",
			input:       "```bash\nfind . -name \"*.log\" | xargs rm\n```",
			expected:    "find . -name \"*.log\" | xargs rm",
			expectError: nil,
		},
		{
			name:        "bash code block with awk",
			input:       "```bash\ncat file.txt | awk '{print $1}'\n```",
			expected:    "cat file.txt | awk '{print $1}'",
			expectError: nil,
		},
		{
			name:        "bash code block with sed",
			input:       "```bash\necho \"hello\" | sed 's/hello/world/'\n```",
			expected:    "echo \"hello\" | sed 's/hello/world/'",
			expectError: nil,
		},
		{
			name:        "bash code block with curl",
			input:       "```bash\ncurl -X POST -H \"Content-Type: application/json\" -d '{\"key\":\"value\"}' http://example.com/api\n```",
			expected:    "curl -X POST -H \"Content-Type: application/json\" -d '{\"key\":\"value\"}' http://example.com/api",
			expectError: nil,
		},
		{
			name:        "bash code block with wget",
			input:       "```bash\nwget -O output.txt http://example.com/file.txt\n```",
			expected:    "wget -O output.txt http://example.com/file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with ssh",
			input:       "```bash\nssh user@host 'ls -la'\n```",
			expected:    "ssh user@host 'ls -la'",
			expectError: nil,
		},
		{
			name:        "bash code block with git",
			input:       "```bash\ngit clone https://github.com/user/repo.git\n```",
			expected:    "git clone https://github.com/user/repo.git",
			expectError: nil,
		},
		{
			name:        "bash code block with docker",
			input:       "```bash\ndocker run -it --rm ubuntu bash\n```",
			expected:    "docker run -it --rm ubuntu bash",
			expectError: nil,
		},
		{
			name:        "bash code block with npm",
			input:       "```bash\nnpm install --save-dev package\n```",
			expected:    "npm install --save-dev package",
			expectError: nil,
		},
		{
			name:        "bash code block with make",
			input:       "```bash\nmake build\n```",
			expected:    "make build",
			expectError: nil,
		},
		{
			name:        "bash code block with go",
			input:       "```bash\ngo build -o app main.go\n```",
			expected:    "go build -o app main.go",
			expectError: nil,
		},
		{
			name:        "bash code block with python",
			input:       "```bash\npython script.py --input file.txt\n```",
			expected:    "python script.py --input file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with node",
			input:       "```bash\nnode server.js\n```",
			expected:    "node server.js",
			expectError: nil,
		},
		{
			name:        "bash code block with jq",
			input:       "```bash\ncat data.json | jq '.key'\n```",
			expected:    "cat data.json | jq '.key'",
			expectError: nil,
		},
		{
			name:        "bash code block with tar",
			input:       "```bash\ntar -czf archive.tar.gz /path/to/dir\n```",
			expected:    "tar -czf archive.tar.gz /path/to/dir",
			expectError: nil,
		},
		{
			name:        "bash code block with gzip",
			input:       "```bash\ngzip file.txt\n```",
			expected:    "gzip file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with chmod",
			input:       "```bash\nchmod +x script.sh\n```",
			expected:    "chmod +x script.sh",
			expectError: nil,
		},
		{
			name:        "bash code block with chown",
			input:       "```bash\nchown user:group file.txt\n```",
			expected:    "chown user:group file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with ln",
			input:       "```bash\nln -s /path/to/target link_name\n```",
			expected:    "ln -s /path/to/target link_name",
			expectError: nil,
		},
		{
			name:        "bash code block with cp",
			input:       "```bash\ncp -r source/ destination/\n```",
			expected:    "cp -r source/ destination/",
			expectError: nil,
		},
		{
			name:        "bash code block with mv",
			input:       "```bash\nmv old_name new_name\n```",
			expected:    "mv old_name new_name",
			expectError: nil,
		},
		{
			name:        "bash code block with rm",
			input:       "```bash\nrm -rf directory/\n```",
			expected:    "rm -rf directory/",
			expectError: nil,
		},
		{
			name:        "bash code block with mkdir",
			input:       "```bash\nmkdir -p path/to/directory\n```",
			expected:    "mkdir -p path/to/directory",
			expectError: nil,
		},
		{
			name:        "bash code block with touch",
			input:       "```bash\ntouch file.txt\n```",
			expected:    "touch file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with cat",
			input:       "```bash\ncat file.txt\n```",
			expected:    "cat file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with less",
			input:       "```bash\nless file.txt\n```",
			expected:    "less file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with head",
			input:       "```bash\nhead -n 10 file.txt\n```",
			expected:    "head -n 10 file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with tail",
			input:       "```bash\ntail -f log.txt\n```",
			expected:    "tail -f log.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with wc",
			input:       "```bash\nwc -l file.txt\n```",
			expected:    "wc -l file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with sort",
			input:       "```bash\nsort -n file.txt\n```",
			expected:    "sort -n file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with uniq",
			input:       "```bash\ncat file.txt | sort | uniq\n```",
			expected:    "cat file.txt | sort | uniq",
			expectError: nil,
		},
		{
			name:        "bash code block with diff",
			input:       "```bash\ndiff file1.txt file2.txt\n```",
			expected:    "diff file1.txt file2.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with ps",
			input:       "```bash\nps aux | grep process\n```",
			expected:    "ps aux | grep process",
			expectError: nil,
		},
		{
			name:        "bash code block with kill",
			input:       "```bash\nkill -9 1234\n```",
			expected:    "kill -9 1234",
			expectError: nil,
		},
		{
			name:        "bash code block with top",
			input:       "```bash\ntop -b -n 1\n```",
			expected:    "top -b -n 1",
			expectError: nil,
		},
		{
			name:        "bash code block with df",
			input:       "```bash\ndf -h\n```",
			expected:    "df -h",
			expectError: nil,
		},
		{
			name:        "bash code block with du",
			input:       "```bash\ndu -sh directory/\n```",
			expected:    "du -sh directory/",
			expectError: nil,
		},
		{
			name:        "bash code block with free",
			input:       "```bash\nfree -h\n```",
			expected:    "free -h",
			expectError: nil,
		},
		{
			name:        "bash code block with uptime",
			input:       "```bash\nuptime\n```",
			expected:    "uptime",
			expectError: nil,
		},
		{
			name:        "bash code block with date",
			input:       "```bash\ndate +\"%Y-%m-%d %H:%M:%S\"\n```",
			expected:    "date +\"%Y-%m-%d %H:%M:%S\"",
			expectError: nil,
		},
		{
			name:        "bash code block with sleep",
			input:       "```bash\nsleep 10\n```",
			expected:    "sleep 10",
			expectError: nil,
		},
		{
			name:        "bash code block with watch",
			input:       "```bash\nwatch -n 1 'ls -la'\n```",
			expected:    "watch -n 1 'ls -la'",
			expectError: nil,
		},
		{
			name:        "bash code block with history",
			input:       "```bash\nhistory | tail -20\n```",
			expected:    "history | tail -20",
			expectError: nil,
		},
		{
			name:        "bash code block with alias",
			input:       "```bash\nalias ll='ls -la'\n```",
			expected:    "alias ll='ls -la'",
			expectError: nil,
		},
		{
			name:        "bash code block with export",
			input:       "```bash\nexport EDITOR=vim\n```",
			expected:    "export EDITOR=vim",
			expectError: nil,
		},
		{
			name:        "bash code block with source",
			input:       "```bash\nsource ~/.bashrc\n```",
			expected:    "source ~/.bashrc",
			expectError: nil,
		},
		{
			name:        "bash code block with dot command",
			input:       "```bash\n. ~/.bashrc\n```",
			expected:    ". ~/.bashrc",
			expectError: nil,
		},
		{
			name:        "bash code block with exec",
			input:       "```bash\nexec bash\n```",
			expected:    "exec bash",
			expectError: nil,
		},
		{
			name:        "bash code block with exit",
			input:       "```bash\nexit 0\n```",
			expected:    "exit 0",
			expectError: nil,
		},
		{
			name:        "bash code block with return",
			input:       "```bash\nreturn 0\n```",
			expected:    "return 0",
			expectError: nil,
		},
		{
			name:        "bash code block with break",
			input:       "```bash\nbreak\n```",
			expected:    "break",
			expectError: nil,
		},
		{
			name:        "bash code block with continue",
			input:       "```bash\ncontinue\n```",
			expected:    "continue",
			expectError: nil,
		},
		{
			name:        "bash code block with shift",
			input:       "```bash\nshift\n```",
			expected:    "shift",
			expectError: nil,
		},
		{
			name:        "bash code block with set",
			input:       "```bash\nset -e\n```",
			expected:    "set -e",
			expectError: nil,
		},
		{
			name:        "bash code block with unset",
			input:       "```bash\nunset MY_VAR\n```",
			expected:    "unset MY_VAR",
			expectError: nil,
		},
		{
			name:        "bash code block with readonly",
			input:       "```bash\nreadonly MY_VAR=\"value\"\n```",
			expected:    "readonly MY_VAR=\"value\"",
			expectError: nil,
		},
		{
			name:        "bash code block with local",
			input:       "```bash\nlocal my_var=\"value\"\n```",
			expected:    "local my_var=\"value\"",
			expectError: nil,
		},
		{
			name:        "bash code block with declare",
			input:       "```bash\ndeclare -a my_array\n```",
			expected:    "declare -a my_array",
			expectError: nil,
		},
		{
			name:        "bash code block with typeset",
			input:       "```bash\ntypeset -i my_int\n```",
			expected:    "typeset -i my_int",
			expectError: nil,
		},
		{
			name:        "bash code block with let",
			input:       "```bash\nlet x=5+5\n```",
			expected:    "let x=5+5",
			expectError: nil,
		},
		{
			name:        "bash code block with eval",
			input:       "```bash\neval \"echo hello\"\n```",
			expected:    "eval \"echo hello\"",
			expectError: nil,
		},
		{
			name:        "bash code block with trap",
			input:       "```bash\ntrap 'echo cleanup' EXIT\n```",
			expected:    "trap 'echo cleanup' EXIT",
			expectError: nil,
		},
		{
			name:        "bash code block with wait",
			input:       "```bash\nwait\n```",
			expected:    "wait",
			expectError: nil,
		},
		{
			name:        "bash code block with jobs",
			input:       "```bash\njobs\n```",
			expected:    "jobs",
			expectError: nil,
		},
		{
			name:        "bash code block with disown",
			input:       "```bash\ndisown %1\n```",
			expected:    "disown %1",
			expectError: nil,
		},
		{
			name:        "bash code block with fg",
			input:       "```bash\nfg %1\n```",
			expected:    "fg %1",
			expectError: nil,
		},
		{
			name:        "bash code block with bg",
			input:       "```bash\nbg %1\n```",
			expected:    "bg %1",
			expectError: nil,
		},
		{
			name:        "bash code block with ulimit",
			input:       "```bash\nulimit -n 4096\n```",
			expected:    "ulimit -n 4096",
			expectError: nil,
		},
		{
			name:        "bash code block with umask",
			input:       "```bash\numask 022\n```",
			expected:    "umask 022",
			expectError: nil,
		},
		{
			name:        "bash code block with stty",
			input:       "```bash\nstty -echo\n```",
			expected:    "stty -echo",
			expectError: nil,
		},
		{
			name:        "bash code block with tput",
			input:       "```bash\ntput clear\n```",
			expected:    "tput clear",
			expectError: nil,
		},
		{
			name:        "bash code block with read",
			input:       "```bash\nread -p \"Enter name: \" name\n```",
			expected:    "read -p \"Enter name: \" name",
			expectError: nil,
		},
		{
			name:        "bash code block with echo",
			input:       "```bash\necho \"Hello, World!\"\n```",
			expected:    "echo \"Hello, World!\"",
			expectError: nil,
		},
		{
			name:        "bash code block with printf",
			input:       "```bash\nprintf \"Name: %s\\n\" \"$name\"\n```",
			expected:    "printf \"Name: %s\\n\" \"$name\"",
			expectError: nil,
		},
		{
			name:        "bash code block with test",
			input:       "```bash\ntest -f file.txt && echo exists\n```",
			expected:    "test -f file.txt && echo exists",
			expectError: nil,
		},
		{
			name:        "bash code block with true",
			input:       "```bash\ntrue\n```",
			expected:    "true",
			expectError: nil,
		},
		{
			name:        "bash code block with false",
			input:       "```bash\nfalse\n```",
			expected:    "false",
			expectError: nil,
		},
		{
			name:        "bash code block with colon",
			input:       "```bash\n:\n```",
			expected:    ":",
			expectError: nil,
		},
		{
			name:        "bash code block with command",
			input:       "```bash\ncommand ls\n```",
			expected:    "command ls",
			expectError: nil,
		},
		{
			name:        "bash code block with builtin",
			input:       "```bash\nbuiltin cd\n```",
			expected:    "builtin cd",
			expectError: nil,
		},
		{
			name:        "bash code block with enable",
			input:       "```bash\nenable -n cd\n```",
			expected:    "enable -n cd",
			expectError: nil,
		},
		{
			name:        "bash code block with type",
			input:       "```bash\ntype ls\n```",
			expected:    "type ls",
			expectError: nil,
		},
		{
			name:        "bash code block with hash",
			input:       "```bash\nhash -r\n```",
			expected:    "hash -r",
			expectError: nil,
		},
		{
			name:        "bash code block with bind",
			input:       "```bash\nbind '\"\\C-l\": clear-screen'\n```",
			expected:    "bind '\"\\C-l\": clear-screen'",
			expectError: nil,
		},
		{
			name:        "bash code block with help",
			input:       "```bash\nhelp cd\n```",
			expected:    "help cd",
			expectError: nil,
		},
		{
			name:        "bash code block with shopt",
			input:       "```bash\nshopt -s cdable_vars\n```",
			expected:    "shopt -s cdable_vars",
			expectError: nil,
		},
		{
			name:        "bash code block with compgen",
			input:       "```bash\ncompgen -c\n```",
			expected:    "compgen -c",
			expectError: nil,
		},
		{
			name:        "bash code block with complete",
			input:       "```bash\ncomplete -F _myfunc mycommand\n```",
			expected:    "complete -F _myfunc mycommand",
			expectError: nil,
		},
		{
			name:        "bash code block with compopt",
			input:       "```bash\ncompopt -o nospace\n```",
			expected:    "compopt -o nospace",
			expectError: nil,
		},
		{
			name:        "bash code block with mapfile",
			input:       "```bash\nmapfile -t my_array < file.txt\n```",
			expected:    "mapfile -t my_array < file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with readarray",
			input:       "```bash\nreadarray -t my_array < file.txt\n```",
			expected:    "readarray -t my_array < file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with select",
			input:       "```bash\nselect opt in option1 option2; do\n  echo $opt\ndone\n```",
			expected:    "select opt in option1 option2; do\n  echo $opt\ndone",
			expectError: nil,
		},
		{
			name:        "bash code block with until",
			input:       "```bash\nuntil [ condition ]; do\n  commands\ndone\n```",
			expected:    "until [ condition ]; do\n  commands\ndone",
			expectError: nil,
		},
		{
			name:        "bash code block with while",
			input:       "```bash\nwhile [ condition ]; do\n  commands\ndone\n```",
			expected:    "while [ condition ]; do\n  commands\ndone",
			expectError: nil,
		},
		{
			name:        "bash code block with time",
			input:       "```bash\ntime ls -la\n```",
			expected:    "time ls -la",
			expectError: nil,
		},
		{
			name:        "bash code block with timeout",
			input:       "```bash\ntimeout 10s command\n```",
			expected:    "timeout 10s command",
			expectError: nil,
		},
		{
			name:        "bash code block with nice",
			input:       "```bash\nnice -n 10 command\n```",
			expected:    "nice -n 10 command",
			expectError: nil,
		},
		{
			name:        "bash code block with renice",
			input:       "```bash\nrenice +5 1234\n```",
			expected:    "renice +5 1234",
			expectError: nil,
		},
		{
			name:        "bash code block with nohup",
			input:       "```bash\nnohup command &\n```",
			expected:    "nohup command &",
			expectError: nil,
		},
		{
			name:        "bash code block with disown",
			input:       "```bash\ndisown -h %1\n```",
			expected:    "disown -h %1",
			expectError: nil,
		},
		{
			name:        "bash code block with screen",
			input:       "```bash\nscreen -S mysession\n```",
			expected:    "screen -S mysession",
			expectError: nil,
		},
		{
			name:        "bash code block with tmux",
			input:       "```bash\ntmux new -s mysession\n```",
			expected:    "tmux new -s mysession",
			expectError: nil,
		},
		{
			name:        "bash code block with batch",
			input:       "```bash\nbatch\n```",
			expected:    "batch",
			expectError: nil,
		},
		{
			name:        "bash code block with at",
			input:       "```bash\nat now + 1 hour\n```",
			expected:    "at now + 1 hour",
			expectError: nil,
		},
		{
			name:        "bash code block with cron",
			input:       "```bash\ncrontab -e\n```",
			expected:    "crontab -e",
			expectError: nil,
		},
		{
			name:        "bash code block with systemd",
			input:       "```bash\nsystemctl start service\n```",
			expected:    "systemctl start service",
			expectError: nil,
		},
		{
			name:        "bash code block with service",
			input:       "```bash\nservice nginx start\n```",
			expected:    "service nginx start",
			expectError: nil,
		},
		{
			name:        "bash code block with initctl",
			input:       "```bash\ninitctl start job\n```",
			expected:    "initctl start job",
			expectError: nil,
		},
		{
			name:        "bash code block with update-rc.d",
			input:       "```bash\nupdate-rc.d service defaults\n```",
			expected:    "update-rc.d service defaults",
			expectError: nil,
		},
		{
			name:        "bash code block with chkconfig",
			input:       "```bash\nchkconfig service on\n```",
			expected:    "chkconfig service on",
			expectError: nil,
		},
		{
			name:        "bash code block with sysctl",
			input:       "```bash\nsysctl -w net.ipv4.ip_forward=1\n```",
			expected:    "sysctl -w net.ipv4.ip_forward=1",
			expectError: nil,
		},
		{
			name:        "bash code block with iptables",
			input:       "```bash\niptables -A INPUT -p tcp --dport 22 -j ACCEPT\n```",
			expected:    "iptables -A INPUT -p tcp --dport 22 -j ACCEPT",
			expectError: nil,
		},
		{
			name:        "bash code block with ufw",
			input:       "```bash\nufw allow 22/tcp\n```",
			expected:    "ufw allow 22/tcp",
			expectError: nil,
		},
		{
			name:        "bash code block with firewall-cmd",
			input:       "```bash\nfirewall-cmd --add-port=22/tcp --permanent\n```",
			expected:    "firewall-cmd --add-port=22/tcp --permanent",
			expectError: nil,
		},
		{
			name:        "bash code block with tcpdump",
			input:       "```bash\ntcpdump -i eth0 port 80\n```",
			expected:    "tcpdump -i eth0 port 80",
			expectError: nil,
		},
		{
			name:        "bash code block with netstat",
			input:       "```bash\nnetstat -tulpn\n```",
			expected:    "netstat -tulpn",
			expectError: nil,
		},
		{
			name:        "bash code block with ss",
			input:       "```bash\nss -tulpn\n```",
			expected:    "ss -tulpn",
			expectError: nil,
		},
		{
			name:        "bash code block with lsof",
			input:       "```bash\nlsof -i :80\n```",
			expected:    "lsof -i :80",
			expectError: nil,
		},
		{
			name:        "bash code block with fuser",
			input:       "```bash\nfuser 80/tcp\n```",
			expected:    "fuser 80/tcp",
			expectError: nil,
		},
		{
			name:        "bash code block with nmap",
			input:       "```bash\nnmap -sV target.com\n```",
			expected:    "nmap -sV target.com",
			expectError: nil,
		},
		{
			name:        "bash code block with ping",
			input:       "```bash\nping -c 4 google.com\n```",
			expected:    "ping -c 4 google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with traceroute",
			input:       "```bash\ntraceroute google.com\n```",
			expected:    "traceroute google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with mtr",
			input:       "```bash\nmtr google.com\n```",
			expected:    "mtr google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with dig",
			input:       "```bash\ndig google.com\n```",
			expected:    "dig google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with nslookup",
			input:       "```bash\nnslookup google.com\n```",
			expected:    "nslookup google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with host",
			input:       "```bash\nhost google.com\n```",
			expected:    "host google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with whois",
			input:       "```bash\nwhois google.com\n```",
			expected:    "whois google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with ip",
			input:       "```bash\nip addr show\n```",
			expected:    "ip addr show",
			expectError: nil,
		},
		{
			name:        "bash code block with ifconfig",
			input:       "```bash\nifconfig\n```",
			expected:    "ifconfig",
			expectError: nil,
		},
		{
			name:        "bash code block with route",
			input:       "```bash\nroute -n\n```",
			expected:    "route -n",
			expectError: nil,
		},
		{
			name:        "bash code block with arp",
			input:       "```bash\narp -a\n```",
			expected:    "arp -a",
			expectError: nil,
		},
		{
			name:        "bash code block with hostname",
			input:       "```bash\nhostname\n```",
			expected:    "hostname",
			expectError: nil,
		},
		{
			name:        "bash code block with domainname",
			input:       "```bash\ndomainname\n```",
			expected:    "domainname",
			expectError: nil,
		},
		{
			name:        "bash code block with dnsdomainname",
			input:       "```bash\ndnsdomainname\n```",
			expected:    "dnsdomainname",
			expectError: nil,
		},
		{
			name:        "bash code block with nisdomainname",
			input:       "```bash\nnisdomainname\n```",
			expected:    "nisdomainname",
			expectError: nil,
		},
		{
			name:        "bash code block with ypdomainname",
			input:       "```bash\nypdomainname\n```",
			expected:    "ypdomainname",
			expectError: nil,
		},
		{
			name:        "bash code block with getent",
			input:       "```bash\ngetent passwd root\n```",
			expected:    "getent passwd root",
			expectError: nil,
		},
		{
			name:        "bash code block with id",
			input:       "```bash\nid\n```",
			expected:    "id",
			expectError: nil,
		},
		{
			name:        "bash code block with whoami",
			input:       "```bash\nwhoami\n```",
			expected:    "whoami",
			expectError: nil,
		},
		{
			name:        "bash code block with who",
			input:       "```bash\nwho\n```",
			expected:    "who",
			expectError: nil,
		},
		{
			name:        "bash code block with w",
			input:       "```bash\nw\n```",
			expected:    "w",
			expectError: nil,
		},
		{
			name:        "bash code block with last",
			input:       "```bash\nlast\n```",
			expected:    "last",
			expectError: nil,
		},
		{
			name:        "bash code block with lastlog",
			input:       "```bash\nlastlog\n```",
			expected:    "lastlog",
			expectError: nil,
		},
		{
			name:        "bash code block with finger",
			input:       "```bash\nfinger user\n```",
			expected:    "finger user",
			expectError: nil,
		},
		{
			name:        "bash code block with pinky",
			input:       "```bash\npinky user\n```",
			expected:    "pinky user",
			expectError: nil,
		},
		{
			name:        "bash code block with users",
			input:       "```bash\nusers\n```",
			expected:    "users",
			expectError: nil,
		},
		{
			name:        "bash code block with groups",
			input:       "```bash\ngroups\n```",
			expected:    "groups",
			expectError: nil,
		},
		{
			name:        "bash code block with newgrp",
			input:       "```bash\nnewgrp group\n```",
			expected:    "newgrp group",
			expectError: nil,
		},
		{
			name:        "bash code block with sg",
			input:       "```bash\nsg group command\n```",
			expected:    "sg group command",
			expectError: nil,
		},
		{
			name:        "bash code block with su",
			input:       "```bash\nsu - user\n```",
			expected:    "su - user",
			expectError: nil,
		},
		{
			name:        "bash code block with sudo",
			input:       "```bash\nsudo -u user command\n```",
			expected:    "sudo -u user command",
			expectError: nil,
		},
		{
			name:        "bash code block with passwd",
			input:       "```bash\npasswd user\n```",
			expected:    "passwd user",
			expectError: nil,
		},
		{
			name:        "bash code block with chpasswd",
			input:       "```bash\necho \"user:password\" | chpasswd\n```",
			expected:    "echo \"user:password\" | chpasswd",
			expectError: nil,
		},
		{
			name:        "bash code block with useradd",
			input:       "```bash\nuseradd -m user\n```",
			expected:    "useradd -m user",
			expectError: nil,
		},
		{
			name:        "bash code block with userdel",
			input:       "```bash\nuserdel -r user\n```",
			expected:    "userdel -r user",
			expectError: nil,
		},
		{
			name:        "bash code block with usermod",
			input:       "```bash\nusermod -aG sudo user\n```",
			expected:    "usermod -aG sudo user",
			expectError: nil,
		},
		{
			name:        "bash code block with groupadd",
			input:       "```bash\ngroupadd group\n```",
			expected:    "groupadd group",
			expectError: nil,
		},
		{
			name:        "bash code block with groupdel",
			input:       "```bash\ngroupdel group\n```",
			expected:    "groupdel group",
			expectError: nil,
		},
		{
			name:        "bash code block with groupmod",
			input:       "```bash\ngroupmod -n newname oldname\n```",
			expected:    "groupmod -n newname oldname",
			expectError: nil,
		},
		{
			name:        "bash code block with gpasswd",
			input:       "```bash\ngpasswd -a user group\n```",
			expected:    "gpasswd -a user group",
			expectError: nil,
		},
		{
			name:        "bash code block with adduser",
			input:       "```bash\nadduser user\n```",
			expected:    "adduser user",
			expectError: nil,
		},
		{
			name:        "bash code block with deluser",
			input:       "```bash\ndeluser user\n```",
			expected:    "deluser user",
			expectError: nil,
		},
		{
			name:        "bash code block with addgroup",
			input:       "```bash\naddgroup group\n```",
			expected:    "addgroup group",
			expectError: nil,
		},
		{
			name:        "bash code block with delgroup",
			input:       "```bash\ndelgroup group\n```",
			expected:    "delgroup group",
			expectError: nil,
		},
		{
			name:        "bash code block with login",
			input:       "```bash\nlogin user\n```",
			expected:    "login user",
			expectError: nil,
		},
		{
			name:        "bash code block with logout",
			input:       "```bash\nlogout\n```",
			expected:    "logout",
			expectError: nil,
		},
		{
			name:        "bash code block with logname",
			input:       "```bash\nlogname\n```",
			expected:    "logname",
			expectError: nil,
		},
		{
			name:        "bash code block with tty",
			input:       "```bash\ntty\n```",
			expected:    "tty",
			expectError: nil,
		},
		{
			name:        "bash code block with stty",
			input:       "```bash\nstty -a\n```",
			expected:    "stty -a",
			expectError: nil,
		},
		{
			name:        "bash code block with mesg",
			input:       "```bash\nmesg y\n```",
			expected:    "mesg y",
			expectError: nil,
		},
		{
			name:        "bash code block with wall",
			input:       "```bash\nwall \"Hello everyone\"\n```",
			expected:    "wall \"Hello everyone\"",
			expectError: nil,
		},
		{
			name:        "bash code block with write",
			input:       "```bash\nwrite user tty\n```",
			expected:    "write user tty",
			expectError: nil,
		},
		{
			name:        "bash code block with talk",
			input:       "```bash\ntalk user@host\n```",
			expected:    "talk user@host",
			expectError: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := ExtractBashCommand(tt.input)

			if tt.expectError != nil {
				if err == nil {
					t.Errorf("ExtractBashCommand() expected error %v, got nil", tt.expectError)
				} else if err != tt.expectError {
					t.Errorf("ExtractBashCommand() expected error %v, got %v", tt.expectError, err)
				}
			} else {
				if err != nil {
					t.Errorf("ExtractBashCommand() unexpected error: %v", err)
				}
				if result != tt.expected {
					t.Errorf("ExtractBashCommand() = %q, want %q", result, tt.expected)
				}
			}
		})
	}
}

func BenchmarkExtractBashCommand(b *testing.B) {
	input := "Here's a command to run:\n```bash\nls -la\n```"
	for i := 0; i < b.N; i++ {
		ExtractBashCommand(input)
	}
}
