package parser

import (
	"testing"
)

func TestExtractBashCommand(t *testing.T) {
	tests := []struct {
		name        string
		input       string
		expected    string
		expectError error
	}{
		{
			name:        "valid bash code block with simple command",
			input:       "Here's a command to run:\n<do>\nls -la\n</do>",
			expected:    "ls -la",
			expectError: nil,
		},
		{
			name:        "valid bash code block with extra whitespace",
			input:       "<do>\n  ls -la  \n</do>",
			expected:    "ls -la",
			expectError: nil,
		},
		{
			name:        "non strict bash code block with multi-line command",
			input:       "<do>\ncd /tmp\nls -la\n</do>",
			expected:    "cd /tmp\nls -la",
			expectError: nil,
		},
		{
			name:        "valid bash code block with complex command",
			input:       "<do>\ngrep -r \"pattern\" /path/to/dir --include=\"*.go\"\n</do>",
			expected:    `grep -r "pattern" /path/to/dir --include="*.go"`,
			expectError: nil,
		},
		{
			name:        "no code blocks",
			input:       "This is just plain text without any code blocks",
			expected:    "",
			expectError: ErrNoBashAction,
		},
		{
			name:        "empty bash code block",
			input:       "<do>\n\n</do>",
			expected:    "",
			expectError: ErrEmptyBashAction,
		},
		{
			name:        "bash code block with only whitespace",
			input:       "<do>\n   \n   \n</do>",
			expected:    "",
			expectError: ErrEmptyBashAction,
		},
		{
			name:        "multiple bash code blocks",
			input:       "<do>\nls -la\n</do>\n\n<do>\ncd /tmp\n</do>",
			expected:    "",
			expectError: ErrMultipleBashActions,
		},
		{
			name:        "bash code block with text before and after",
			input:       "Some text before\n<do>\necho hello\n</do>\nSome text after",
			expected:    "echo hello",
			expectError: nil,
		},
		{
			name:        "bash code block with pipe command",
			input:       "<do>\ncat file.txt | grep pattern\n</do>",
			expected:    "cat file.txt | grep pattern",
			expectError: nil,
		},
		{
			name:        "bash code block with command substitution",
			input:       "<do>\necho $(date)\n</do>",
			expected:    "echo $(date)",
			expectError: nil,
		},
		{
			name:        "bash code block with heredoc",
			input:       "<do>\ncat <<EOF\nHello World\nEOF\n</do>",
			expected:    "cat <<EOF\nHello World\nEOF",
			expectError: nil,
		},
		{
			name:        "bash code block with environment variable",
			input:       "<do>\nexport PATH=/usr/local/bin:$PATH\n</do>",
			expected:    "export PATH=/usr/local/bin:$PATH",
			expectError: nil,
		},
		{
			name:        "bash code block with background job",
			input:       "<do>\nnohup ./script.sh &\n</do>",
			expected:    "nohup ./script.sh &",
			expectError: nil,
		},
		{
			name:        "bash code block with conditional",
			input:       "<do>\nif [ -f file.txt ]; then\n  cat file.txt\nfi\n</do>",
			expected:    "if [ -f file.txt ]; then\n  cat file.txt\nfi",
			expectError: nil,
		},
		{
			name:        "bash code block with loop",
			input:       "<do>\nfor i in {1..5}; do\n  echo $i\ndone\n</do>",
			expected:    "for i in {1..5}; do\n  echo $i\ndone",
			expectError: nil,
		},
		{
			name:        "bash code block with function definition",
			input:       "<do>\nfunction greet() {\n  echo \"Hello, $1!\"\n}\ngreet World\n</do>",
			expected:    "function greet() {\n  echo \"Hello, $1!\"\n}\ngreet World",
			expectError: nil,
		},
		{
			name:        "bash code block with array",
			input:       "<do>\narr=(one two three)\necho ${arr[0]}\n</do>",
			expected:    "arr=(one two three)\necho ${arr[0]}",
			expectError: nil,
		},
		{
			name:        "bash code block with case statement",
			input:       "<do>\ncase $1 in\n  start) echo Starting;;\n  stop) echo Stopping;;\n  *) echo Usage;;\nesac\n</do>",
			expected:    "case $1 in\n  start) echo Starting;;\n  stop) echo Stopping;;\n  *) echo Usage;;\nesac",
			expectError: nil,
		},
		{
			name:        "bash code block with sudo command",
			input:       "<do>\nsudo apt-get update\n</do>",
			expected:    "sudo apt-get update",
			expectError: nil,
		},
		{
			name:        "bash code block with redirection",
			input:       "<do>\necho output > file.txt\n</do>",
			expected:    "echo output > file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with append redirection",
			input:       "<do>\necho more output >> file.txt\n</do>",
			expected:    "echo more output >> file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with error redirection",
			input:       "<do>\ncmd 2> error.log\n</do>",
			expected:    "cmd 2> error.log",
			expectError: nil,
		},
		{
			name:        "bash code block with combined redirection",
			input:       "<do>\ncmd > output.log 2>&1\n</do>",
			expected:    "cmd > output.log 2>&1",
			expectError: nil,
		},
		{
			name:        "bash code block with logical AND",
			input:       "<do>\ncmd1 && cmd2\n</do>",
			expected:    "cmd1 && cmd2",
			expectError: nil,
		},
		{
			name:        "bash code block with logical OR",
			input:       "<do>\ncmd1 || cmd2\n</do>",
			expected:    "cmd1 || cmd2",
			expectError: nil,
		},
		{
			name:        "bash code block with semicolon separator",
			input:       "<do>\ncmd1; cmd2; cmd3\n</do>",
			expected:    "cmd1; cmd2; cmd3",
			expectError: nil,
		},
		{
			name:        "bash code block with command grouping",
			input:       "<do>\n{ cmd1; cmd2; }\n</do>",
			expected:    "{ cmd1; cmd2; }",
			expectError: nil,
		},
		{
			name:        "bash code block with subshell",
			input:       "<do>\n(cmd1; cmd2)\n</do>",
			expected:    "(cmd1; cmd2)",
			expectError: nil,
		},
		{
			name:        "bash code block with variable assignment",
			input:       "<do>\nMY_VAR=\"some value\"\necho $MY_VAR\n</do>",
			expected:    "MY_VAR=\"some value\"\necho $MY_VAR",
			expectError: nil,
		},
		{
			name:        "bash code block with arithmetic",
			input:       "<do>\necho $((1 + 2))\n</do>",
			expected:    "echo $((1 + 2))",
			expectError: nil,
		},
		{
			name:        "bash code block with test command",
			input:       "<do>\n[ -f file.txt ] && echo exists\n</do>",
			expected:    "[ -f file.txt ] && echo exists",
			expectError: nil,
		},
		{
			name:        "bash code block with double bracket test",
			input:       "<do>\n[[ -f file.txt ]] && echo exists\n</do>",
			expected:    "[[ -f file.txt ]] && echo exists",
			expectError: nil,
		},
		{
			name:        "bash code block with find command",
			input:       "<do>\nfind /path -name \"*.go\" -type f\n</do>",
			expected:    "find /path -name \"*.go\" -type f",
			expectError: nil,
		},
		{
			name:        "bash code block with xargs",
			input:       "<do>\nfind . -name \"*.log\" | xargs rm\n</do>",
			expected:    "find . -name \"*.log\" | xargs rm",
			expectError: nil,
		},
		{
			name:        "bash code block with awk",
			input:       "<do>\ncat file.txt | awk '{print $1}'\n</do>",
			expected:    "cat file.txt | awk '{print $1}'",
			expectError: nil,
		},
		{
			name:        "bash code block with sed",
			input:       "<do>\necho \"hello\" | sed 's/hello/world/'\n</do>",
			expected:    "echo \"hello\" | sed 's/hello/world/'",
			expectError: nil,
		},
		{
			name:        "bash code block with curl",
			input:       "<do>\ncurl -X POST -H \"Content-Type: application/json\" -d '{\"key\":\"value\"}' http://example.com/api\n</do>",
			expected:    "curl -X POST -H \"Content-Type: application/json\" -d '{\"key\":\"value\"}' http://example.com/api",
			expectError: nil,
		},
		{
			name:        "bash code block with wget",
			input:       "<do>\nwget -O output.txt http://example.com/file.txt\n</do>",
			expected:    "wget -O output.txt http://example.com/file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with ssh",
			input:       "<do>\nssh user@host 'ls -la'\n</do>",
			expected:    "ssh user@host 'ls -la'",
			expectError: nil,
		},
		{
			name:        "bash code block with git",
			input:       "<do>\ngit clone https://github.com/user/repo.git\n</do>",
			expected:    "git clone https://github.com/user/repo.git",
			expectError: nil,
		},
		{
			name:        "bash code block with docker",
			input:       "<do>\ndocker run -it --rm ubuntu bash\n</do>",
			expected:    "docker run -it --rm ubuntu bash",
			expectError: nil,
		},
		{
			name:        "bash code block with npm",
			input:       "<do>\nnpm install --save-dev package\n</do>",
			expected:    "npm install --save-dev package",
			expectError: nil,
		},
		{
			name:        "bash code block with make",
			input:       "<do>\nmake build\n</do>",
			expected:    "make build",
			expectError: nil,
		},
		{
			name:        "bash code block with go",
			input:       "<do>\ngo build -o app main.go\n</do>",
			expected:    "go build -o app main.go",
			expectError: nil,
		},
		{
			name:        "bash code block with python",
			input:       "<do>\npython script.py --input file.txt\n</do>",
			expected:    "python script.py --input file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with node",
			input:       "<do>\nnode server.js\n</do>",
			expected:    "node server.js",
			expectError: nil,
		},
		{
			name:        "bash code block with jq",
			input:       "<do>\ncat data.json | jq '.key'\n</do>",
			expected:    "cat data.json | jq '.key'",
			expectError: nil,
		},
		{
			name:        "bash code block with tar",
			input:       "<do>\ntar -czf archive.tar.gz /path/to/dir\n</do>",
			expected:    "tar -czf archive.tar.gz /path/to/dir",
			expectError: nil,
		},
		{
			name:        "bash code block with gzip",
			input:       "<do>\ngzip file.txt\n</do>",
			expected:    "gzip file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with chmod",
			input:       "<do>\nchmod +x script.sh\n</do>",
			expected:    "chmod +x script.sh",
			expectError: nil,
		},
		{
			name:        "bash code block with chown",
			input:       "<do>\nchown user:group file.txt\n</do>",
			expected:    "chown user:group file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with ln",
			input:       "<do>\nln -s /path/to/target link_name\n</do>",
			expected:    "ln -s /path/to/target link_name",
			expectError: nil,
		},
		{
			name:        "bash code block with cp",
			input:       "<do>\ncp -r source/ destination/\n</do>",
			expected:    "cp -r source/ destination/",
			expectError: nil,
		},
		{
			name:        "bash code block with mv",
			input:       "<do>\nmv old_name new_name\n</do>",
			expected:    "mv old_name new_name",
			expectError: nil,
		},
		{
			name:        "bash code block with rm",
			input:       "<do>\nrm -rf directory/\n</do>",
			expected:    "rm -rf directory/",
			expectError: nil,
		},
		{
			name:        "bash code block with mkdir",
			input:       "<do>\nmkdir -p path/to/directory\n</do>",
			expected:    "mkdir -p path/to/directory",
			expectError: nil,
		},
		{
			name:        "bash code block with touch",
			input:       "<do>\ntouch file.txt\n</do>",
			expected:    "touch file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with cat",
			input:       "<do>\ncat file.txt\n</do>",
			expected:    "cat file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with less",
			input:       "<do>\nless file.txt\n</do>",
			expected:    "less file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with head",
			input:       "<do>\nhead -n 10 file.txt\n</do>",
			expected:    "head -n 10 file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with tail",
			input:       "<do>\ntail -f log.txt\n</do>",
			expected:    "tail -f log.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with wc",
			input:       "<do>\nwc -l file.txt\n</do>",
			expected:    "wc -l file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with sort",
			input:       "<do>\nsort -n file.txt\n</do>",
			expected:    "sort -n file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with uniq",
			input:       "<do>\ncat file.txt | sort | uniq\n</do>",
			expected:    "cat file.txt | sort | uniq",
			expectError: nil,
		},
		{
			name:        "bash code block with diff",
			input:       "<do>\ndiff file1.txt file2.txt\n</do>",
			expected:    "diff file1.txt file2.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with ps",
			input:       "<do>\nps aux | grep process\n</do>",
			expected:    "ps aux | grep process",
			expectError: nil,
		},
		{
			name:        "bash code block with kill",
			input:       "<do>\nkill -9 1234\n</do>",
			expected:    "kill -9 1234",
			expectError: nil,
		},
		{
			name:        "bash code block with top",
			input:       "<do>\ntop -b -n 1\n</do>",
			expected:    "top -b -n 1",
			expectError: nil,
		},
		{
			name:        "bash code block with df",
			input:       "<do>\ndf -h\n</do>",
			expected:    "df -h",
			expectError: nil,
		},
		{
			name:        "bash code block with du",
			input:       "<do>\ndu -sh directory/\n</do>",
			expected:    "du -sh directory/",
			expectError: nil,
		},
		{
			name:        "bash code block with free",
			input:       "<do>\nfree -h\n</do>",
			expected:    "free -h",
			expectError: nil,
		},
		{
			name:        "bash code block with uptime",
			input:       "<do>\nuptime\n</do>",
			expected:    "uptime",
			expectError: nil,
		},
		{
			name:        "bash code block with date",
			input:       "<do>\ndate +\"%Y-%m-%d %H:%M:%S\"\n</do>",
			expected:    "date +\"%Y-%m-%d %H:%M:%S\"",
			expectError: nil,
		},
		{
			name:        "bash code block with sleep",
			input:       "<do>\nsleep 10\n</do>",
			expected:    "sleep 10",
			expectError: nil,
		},
		{
			name:        "bash code block with watch",
			input:       "<do>\nwatch -n 1 'ls -la'\n</do>",
			expected:    "watch -n 1 'ls -la'",
			expectError: nil,
		},
		{
			name:        "bash code block with history",
			input:       "<do>\nhistory | tail -20\n</do>",
			expected:    "history | tail -20",
			expectError: nil,
		},
		{
			name:        "bash code block with alias",
			input:       "<do>\nalias ll='ls -la'\n</do>",
			expected:    "alias ll='ls -la'",
			expectError: nil,
		},
		{
			name:        "bash code block with export",
			input:       "<do>\nexport EDITOR=vim\n</do>",
			expected:    "export EDITOR=vim",
			expectError: nil,
		},
		{
			name:        "bash code block with source",
			input:       "<do>\nsource ~/.bashrc\n</do>",
			expected:    "source ~/.bashrc",
			expectError: nil,
		},
		{
			name:        "bash code block with dot command",
			input:       "<do>\n. ~/.bashrc\n</do>",
			expected:    ". ~/.bashrc",
			expectError: nil,
		},
		{
			name:        "bash code block with exec",
			input:       "<do>\nexec bash\n</do>",
			expected:    "exec bash",
			expectError: nil,
		},
		{
			name:        "bash code block with exit",
			input:       "<do>\nexit 0\n</do>",
			expected:    "exit 0",
			expectError: nil,
		},
		{
			name:        "bash code block with return",
			input:       "<do>\nreturn 0\n</do>",
			expected:    "return 0",
			expectError: nil,
		},
		{
			name:        "bash code block with break",
			input:       "<do>\nbreak\n</do>",
			expected:    "break",
			expectError: nil,
		},
		{
			name:        "bash code block with continue",
			input:       "<do>\ncontinue\n</do>",
			expected:    "continue",
			expectError: nil,
		},
		{
			name:        "bash code block with shift",
			input:       "<do>\nshift\n</do>",
			expected:    "shift",
			expectError: nil,
		},
		{
			name:        "bash code block with set",
			input:       "<do>\nset -e\n</do>",
			expected:    "set -e",
			expectError: nil,
		},
		{
			name:        "bash code block with unset",
			input:       "<do>\nunset MY_VAR\n</do>",
			expected:    "unset MY_VAR",
			expectError: nil,
		},
		{
			name:        "bash code block with readonly",
			input:       "<do>\nreadonly MY_VAR=\"value\"\n</do>",
			expected:    "readonly MY_VAR=\"value\"",
			expectError: nil,
		},
		{
			name:        "bash code block with local",
			input:       "<do>\nlocal my_var=\"value\"\n</do>",
			expected:    "local my_var=\"value\"",
			expectError: nil,
		},
		{
			name:        "bash code block with declare",
			input:       "<do>\ndeclare -a my_array\n</do>",
			expected:    "declare -a my_array",
			expectError: nil,
		},
		{
			name:        "bash code block with typeset",
			input:       "<do>\ntypeset -i my_int\n</do>",
			expected:    "typeset -i my_int",
			expectError: nil,
		},
		{
			name:        "bash code block with let",
			input:       "<do>\nlet x=5+5\n</do>",
			expected:    "let x=5+5",
			expectError: nil,
		},
		{
			name:        "bash code block with eval",
			input:       "<do>\neval \"echo hello\"\n</do>",
			expected:    "eval \"echo hello\"",
			expectError: nil,
		},
		{
			name:        "bash code block with trap",
			input:       "<do>\ntrap 'echo cleanup' EXIT\n</do>",
			expected:    "trap 'echo cleanup' EXIT",
			expectError: nil,
		},
		{
			name:        "bash code block with wait",
			input:       "<do>\nwait\n</do>",
			expected:    "wait",
			expectError: nil,
		},
		{
			name:        "bash code block with jobs",
			input:       "<do>\njobs\n</do>",
			expected:    "jobs",
			expectError: nil,
		},
		{
			name:        "bash code block with disown",
			input:       "<do>\ndisown %1\n</do>",
			expected:    "disown %1",
			expectError: nil,
		},
		{
			name:        "bash code block with fg",
			input:       "<do>\nfg %1\n</do>",
			expected:    "fg %1",
			expectError: nil,
		},
		{
			name:        "bash code block with bg",
			input:       "<do>\nbg %1\n</do>",
			expected:    "bg %1",
			expectError: nil,
		},
		{
			name:        "bash code block with ulimit",
			input:       "<do>\nulimit -n 4096\n</do>",
			expected:    "ulimit -n 4096",
			expectError: nil,
		},
		{
			name:        "bash code block with umask",
			input:       "<do>\numask 022\n</do>",
			expected:    "umask 022",
			expectError: nil,
		},
		{
			name:        "bash code block with stty",
			input:       "<do>\nstty -echo\n</do>",
			expected:    "stty -echo",
			expectError: nil,
		},
		{
			name:        "bash code block with tput",
			input:       "<do>\ntput clear\n</do>",
			expected:    "tput clear",
			expectError: nil,
		},
		{
			name:        "bash code block with read",
			input:       "<do>\nread -p \"Enter name: \" name\n</do>",
			expected:    "read -p \"Enter name: \" name",
			expectError: nil,
		},
		{
			name:        "bash code block with echo",
			input:       "<do>\necho \"Hello, World!\"\n</do>",
			expected:    "echo \"Hello, World!\"",
			expectError: nil,
		},
		{
			name:        "bash code block with printf",
			input:       "<do>\nprintf \"Name: %s\\n\" \"$name\"\n</do>",
			expected:    "printf \"Name: %s\\n\" \"$name\"",
			expectError: nil,
		},
		{
			name:        "bash code block with test",
			input:       "<do>\ntest -f file.txt && echo exists\n</do>",
			expected:    "test -f file.txt && echo exists",
			expectError: nil,
		},
		{
			name:        "bash code block with true",
			input:       "<do>\ntrue\n</do>",
			expected:    "true",
			expectError: nil,
		},
		{
			name:        "bash code block with false",
			input:       "<do>\nfalse\n</do>",
			expected:    "false",
			expectError: nil,
		},
		{
			name:        "bash code block with colon",
			input:       "<do>\n:\n</do>",
			expected:    ":",
			expectError: nil,
		},
		{
			name:        "bash code block with command",
			input:       "<do>\ncommand ls\n</do>",
			expected:    "command ls",
			expectError: nil,
		},
		{
			name:        "bash code block with builtin",
			input:       "<do>\nbuiltin cd\n</do>",
			expected:    "builtin cd",
			expectError: nil,
		},
		{
			name:        "bash code block with enable",
			input:       "<do>\nenable -n cd\n</do>",
			expected:    "enable -n cd",
			expectError: nil,
		},
		{
			name:        "bash code block with type",
			input:       "<do>\ntype ls\n</do>",
			expected:    "type ls",
			expectError: nil,
		},
		{
			name:        "bash code block with hash",
			input:       "<do>\nhash -r\n</do>",
			expected:    "hash -r",
			expectError: nil,
		},
		{
			name:        "bash code block with bind",
			input:       "<do>\nbind '\"\\C-l\": clear-screen'\n</do>",
			expected:    "bind '\"\\C-l\": clear-screen'",
			expectError: nil,
		},
		{
			name:        "bash code block with help",
			input:       "<do>\nhelp cd\n</do>",
			expected:    "help cd",
			expectError: nil,
		},
		{
			name:        "bash code block with shopt",
			input:       "<do>\nshopt -s cdable_vars\n</do>",
			expected:    "shopt -s cdable_vars",
			expectError: nil,
		},
		{
			name:        "bash code block with compgen",
			input:       "<do>\ncompgen -c\n</do>",
			expected:    "compgen -c",
			expectError: nil,
		},
		{
			name:        "bash code block with complete",
			input:       "<do>\ncomplete -F _myfunc mycommand\n</do>",
			expected:    "complete -F _myfunc mycommand",
			expectError: nil,
		},
		{
			name:        "bash code block with compopt",
			input:       "<do>\ncompopt -o nospace\n</do>",
			expected:    "compopt -o nospace",
			expectError: nil,
		},
		{
			name:        "bash code block with mapfile",
			input:       "<do>\nmapfile -t my_array < file.txt\n</do>",
			expected:    "mapfile -t my_array < file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with readarray",
			input:       "<do>\nreadarray -t my_array < file.txt\n</do>",
			expected:    "readarray -t my_array < file.txt",
			expectError: nil,
		},
		{
			name:        "bash code block with select",
			input:       "<do>\nselect opt in option1 option2; do\n  echo $opt\ndone\n</do>",
			expected:    "select opt in option1 option2; do\n  echo $opt\ndone",
			expectError: nil,
		},
		{
			name:        "bash code block with until",
			input:       "<do>\nuntil [ condition ]; do\n  commands\ndone\n</do>",
			expected:    "until [ condition ]; do\n  commands\ndone",
			expectError: nil,
		},
		{
			name:        "bash code block with while",
			input:       "<do>\nwhile [ condition ]; do\n  commands\ndone\n</do>",
			expected:    "while [ condition ]; do\n  commands\ndone",
			expectError: nil,
		},
		{
			name:        "bash code block with time",
			input:       "<do>\ntime ls -la\n</do>",
			expected:    "time ls -la",
			expectError: nil,
		},
		{
			name:        "bash code block with timeout",
			input:       "<do>\ntimeout 10s command\n</do>",
			expected:    "timeout 10s command",
			expectError: nil,
		},
		{
			name:        "bash code block with nice",
			input:       "<do>\nnice -n 10 command\n</do>",
			expected:    "nice -n 10 command",
			expectError: nil,
		},
		{
			name:        "bash code block with renice",
			input:       "<do>\nrenice +5 1234\n</do>",
			expected:    "renice +5 1234",
			expectError: nil,
		},
		{
			name:        "bash code block with nohup",
			input:       "<do>\nnohup command &\n</do>",
			expected:    "nohup command &",
			expectError: nil,
		},
		{
			name:        "bash code block with disown",
			input:       "<do>\ndisown -h %1\n</do>",
			expected:    "disown -h %1",
			expectError: nil,
		},
		{
			name:        "bash code block with screen",
			input:       "<do>\nscreen -S mysession\n</do>",
			expected:    "screen -S mysession",
			expectError: nil,
		},
		{
			name:        "bash code block with tmux",
			input:       "<do>\ntmux new -s mysession\n</do>",
			expected:    "tmux new -s mysession",
			expectError: nil,
		},
		{
			name:        "bash code block with batch",
			input:       "<do>\nbatch\n</do>",
			expected:    "batch",
			expectError: nil,
		},
		{
			name:        "bash code block with at",
			input:       "<do>\nat now + 1 hour\n</do>",
			expected:    "at now + 1 hour",
			expectError: nil,
		},
		{
			name:        "bash code block with cron",
			input:       "<do>\ncrontab -e\n</do>",
			expected:    "crontab -e",
			expectError: nil,
		},
		{
			name:        "bash code block with systemd",
			input:       "<do>\nsystemctl start service\n</do>",
			expected:    "systemctl start service",
			expectError: nil,
		},
		{
			name:        "bash code block with service",
			input:       "<do>\nservice nginx start\n</do>",
			expected:    "service nginx start",
			expectError: nil,
		},
		{
			name:        "bash code block with initctl",
			input:       "<do>\ninitctl start job\n</do>",
			expected:    "initctl start job",
			expectError: nil,
		},
		{
			name:        "bash code block with update-rc.d",
			input:       "<do>\nupdate-rc.d service defaults\n</do>",
			expected:    "update-rc.d service defaults",
			expectError: nil,
		},
		{
			name:        "bash code block with chkconfig",
			input:       "<do>\nchkconfig service on\n</do>",
			expected:    "chkconfig service on",
			expectError: nil,
		},
		{
			name:        "bash code block with sysctl",
			input:       "<do>\nsysctl -w net.ipv4.ip_forward=1\n</do>",
			expected:    "sysctl -w net.ipv4.ip_forward=1",
			expectError: nil,
		},
		{
			name:        "bash code block with iptables",
			input:       "<do>\niptables -A INPUT -p tcp --dport 22 -j ACCEPT\n</do>",
			expected:    "iptables -A INPUT -p tcp --dport 22 -j ACCEPT",
			expectError: nil,
		},
		{
			name:        "bash code block with ufw",
			input:       "<do>\nufw allow 22/tcp\n</do>",
			expected:    "ufw allow 22/tcp",
			expectError: nil,
		},
		{
			name:        "bash code block with firewall-cmd",
			input:       "<do>\nfirewall-cmd --add-port=22/tcp --permanent\n</do>",
			expected:    "firewall-cmd --add-port=22/tcp --permanent",
			expectError: nil,
		},
		{
			name:        "bash code block with tcpdump",
			input:       "<do>\ntcpdump -i eth0 port 80\n</do>",
			expected:    "tcpdump -i eth0 port 80",
			expectError: nil,
		},
		{
			name:        "bash code block with netstat",
			input:       "<do>\nnetstat -tulpn\n</do>",
			expected:    "netstat -tulpn",
			expectError: nil,
		},
		{
			name:        "bash code block with ss",
			input:       "<do>\nss -tulpn\n</do>",
			expected:    "ss -tulpn",
			expectError: nil,
		},
		{
			name:        "bash code block with lsof",
			input:       "<do>\nlsof -i :80\n</do>",
			expected:    "lsof -i :80",
			expectError: nil,
		},
		{
			name:        "bash code block with fuser",
			input:       "<do>\nfuser 80/tcp\n</do>",
			expected:    "fuser 80/tcp",
			expectError: nil,
		},
		{
			name:        "bash code block with nmap",
			input:       "<do>\nnmap -sV target.com\n</do>",
			expected:    "nmap -sV target.com",
			expectError: nil,
		},
		{
			name:        "bash code block with ping",
			input:       "<do>\nping -c 4 google.com\n</do>",
			expected:    "ping -c 4 google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with traceroute",
			input:       "<do>\ntraceroute google.com\n</do>",
			expected:    "traceroute google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with mtr",
			input:       "<do>\nmtr google.com\n</do>",
			expected:    "mtr google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with dig",
			input:       "<do>\ndig google.com\n</do>",
			expected:    "dig google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with nslookup",
			input:       "<do>\nnslookup google.com\n</do>",
			expected:    "nslookup google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with host",
			input:       "<do>\nhost google.com\n</do>",
			expected:    "host google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with whois",
			input:       "<do>\nwhois google.com\n</do>",
			expected:    "whois google.com",
			expectError: nil,
		},
		{
			name:        "bash code block with ip",
			input:       "<do>\nip addr show\n</do>",
			expected:    "ip addr show",
			expectError: nil,
		},
		{
			name:        "bash code block with ifconfig",
			input:       "<do>\nifconfig\n</do>",
			expected:    "ifconfig",
			expectError: nil,
		},
		{
			name:        "bash code block with route",
			input:       "<do>\nroute -n\n</do>",
			expected:    "route -n",
			expectError: nil,
		},
		{
			name:        "bash code block with arp",
			input:       "<do>\narp -a\n</do>",
			expected:    "arp -a",
			expectError: nil,
		},
		{
			name:        "bash code block with hostname",
			input:       "<do>\nhostname\n</do>",
			expected:    "hostname",
			expectError: nil,
		},
		{
			name:        "bash code block with domainname",
			input:       "<do>\ndomainname\n</do>",
			expected:    "domainname",
			expectError: nil,
		},
		{
			name:        "bash code block with dnsdomainname",
			input:       "<do>\ndnsdomainname\n</do>",
			expected:    "dnsdomainname",
			expectError: nil,
		},
		{
			name:        "bash code block with nisdomainname",
			input:       "<do>\nnisdomainname\n</do>",
			expected:    "nisdomainname",
			expectError: nil,
		},
		{
			name:        "bash code block with ypdomainname",
			input:       "<do>\nypdomainname\n</do>",
			expected:    "ypdomainname",
			expectError: nil,
		},
		{
			name:        "bash code block with getent",
			input:       "<do>\ngetent passwd root\n</do>",
			expected:    "getent passwd root",
			expectError: nil,
		},
		{
			name:        "bash code block with id",
			input:       "<do>\nid\n</do>",
			expected:    "id",
			expectError: nil,
		},
		{
			name:        "bash code block with whoami",
			input:       "<do>\nwhoami\n</do>",
			expected:    "whoami",
			expectError: nil,
		},
		{
			name:        "bash code block with who",
			input:       "<do>\nwho\n</do>",
			expected:    "who",
			expectError: nil,
		},
		{
			name:        "bash code block with w",
			input:       "<do>\nw\n</do>",
			expected:    "w",
			expectError: nil,
		},
		{
			name:        "bash code block with last",
			input:       "<do>\nlast\n</do>",
			expected:    "last",
			expectError: nil,
		},
		{
			name:        "bash code block with lastlog",
			input:       "<do>\nlastlog\n</do>",
			expected:    "lastlog",
			expectError: nil,
		},
		{
			name:        "bash code block with finger",
			input:       "<do>\nfinger user\n</do>",
			expected:    "finger user",
			expectError: nil,
		},
		{
			name:        "bash code block with pinky",
			input:       "<do>\npinky user\n</do>",
			expected:    "pinky user",
			expectError: nil,
		},
		{
			name:        "bash code block with users",
			input:       "<do>\nusers\n</do>",
			expected:    "users",
			expectError: nil,
		},
		{
			name:        "bash code block with groups",
			input:       "<do>\ngroups\n</do>",
			expected:    "groups",
			expectError: nil,
		},
		{
			name:        "bash code block with newgrp",
			input:       "<do>\nnewgrp group\n</do>",
			expected:    "newgrp group",
			expectError: nil,
		},
		{
			name:        "bash code block with sg",
			input:       "<do>\nsg group command\n</do>",
			expected:    "sg group command",
			expectError: nil,
		},
		{
			name:        "bash code block with su",
			input:       "<do>\nsu - user\n</do>",
			expected:    "su - user",
			expectError: nil,
		},
		{
			name:        "bash code block with sudo",
			input:       "<do>\nsudo -u user command\n</do>",
			expected:    "sudo -u user command",
			expectError: nil,
		},
		{
			name:        "bash code block with passwd",
			input:       "<do>\npasswd user\n</do>",
			expected:    "passwd user",
			expectError: nil,
		},
		{
			name:        "bash code block with chpasswd",
			input:       "<do>\necho \"user:password\" | chpasswd\n</do>",
			expected:    "echo \"user:password\" | chpasswd",
			expectError: nil,
		},
		{
			name:        "bash code block with useradd",
			input:       "<do>\nuseradd -m user\n</do>",
			expected:    "useradd -m user",
			expectError: nil,
		},
		{
			name:        "bash code block with userdel",
			input:       "<do>\nuserdel -r user\n</do>",
			expected:    "userdel -r user",
			expectError: nil,
		},
		{
			name:        "bash code block with usermod",
			input:       "<do>\nusermod -aG sudo user\n</do>",
			expected:    "usermod -aG sudo user",
			expectError: nil,
		},
		{
			name:        "bash code block with groupadd",
			input:       "<do>\ngroupadd group\n</do>",
			expected:    "groupadd group",
			expectError: nil,
		},
		{
			name:        "bash code block with groupdel",
			input:       "<do>\ngroupdel group\n</do>",
			expected:    "groupdel group",
			expectError: nil,
		},
		{
			name:        "bash code block with groupmod",
			input:       "<do>\ngroupmod -n newname oldname\n</do>",
			expected:    "groupmod -n newname oldname",
			expectError: nil,
		},
		{
			name:        "bash code block with gpasswd",
			input:       "<do>\ngpasswd -a user group\n</do>",
			expected:    "gpasswd -a user group",
			expectError: nil,
		},
		{
			name:        "bash code block with adduser",
			input:       "<do>\nadduser user\n</do>",
			expected:    "adduser user",
			expectError: nil,
		},
		{
			name:        "bash code block with deluser",
			input:       "<do>\ndeluser user\n</do>",
			expected:    "deluser user",
			expectError: nil,
		},
		{
			name:        "bash code block with addgroup",
			input:       "<do>\naddgroup group\n</do>",
			expected:    "addgroup group",
			expectError: nil,
		},
		{
			name:        "bash code block with delgroup",
			input:       "<do>\ndelgroup group\n</do>",
			expected:    "delgroup group",
			expectError: nil,
		},
		{
			name:        "bash code block with login",
			input:       "<do>\nlogin user\n</do>",
			expected:    "login user",
			expectError: nil,
		},
		{
			name:        "bash code block with logout",
			input:       "<do>\nlogout\n</do>",
			expected:    "logout",
			expectError: nil,
		},
		{
			name:        "bash code block with logname",
			input:       "<do>\nlogname\n</do>",
			expected:    "logname",
			expectError: nil,
		},
		{
			name:        "bash code block with tty",
			input:       "<do>\ntty\n</do>",
			expected:    "tty",
			expectError: nil,
		},
		{
			name:        "bash code block with stty",
			input:       "<do>\nstty -a\n</do>",
			expected:    "stty -a",
			expectError: nil,
		},
		{
			name:        "bash code block with mesg",
			input:       "<do>\nmesg y\n</do>",
			expected:    "mesg y",
			expectError: nil,
		},
		{
			name:        "bash code block with wall",
			input:       "<do>\nwall \"Hello everyone\"\n</do>",
			expected:    "wall \"Hello everyone\"",
			expectError: nil,
		},
		{
			name:        "bash code block with write",
			input:       "<do>\nwrite user tty\n</do>",
			expected:    "write user tty",
			expectError: nil,
		},
		{
			name:        "bash code block with talk",
			input:       "<do>\ntalk user@host\n</do>",
			expected:    "talk user@host",
			expectError: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := ExtractBashCommand(tt.input)

			if tt.expectError != nil {
				if err == nil {
					t.Errorf("ExtractBashCommand() expected error %v, got nil", tt.expectError)
				} else if err != tt.expectError {
					t.Errorf("ExtractBashCommand() expected error %v, got %v", tt.expectError, err)
				}
			} else {
				if err != nil {
					t.Errorf("ExtractBashCommand() unexpected error: %v", err)
				}
				if result != tt.expected {
					t.Errorf("ExtractBashCommand() = %q, want %q", result, tt.expected)
				}
			}
		})
	}
}

func BenchmarkExtractBashCommand(b *testing.B) {
	input := "Here's a command to run:\n<do>\nls -la\n</do>"
	for i := 0; i < b.N; i++ {
		ExtractBashCommand(input)
	}
}
